### ISSUE TITLE
openacc and mpi+openacc applications

### ISSUE THREAD

**Issue by gihanmudalige** [OP-DSL/OPS#54]
Some of the openacc and mpi_openacc parallelisations of the application in the OPS repository either does not give the expected output or does not run/seg-faults/produces errors. The following is a list that fails on Octon :
1. CloverLeaf_3D and CloverLeaf_3D_HDF5 (C/C++ API) : openacc and mpi+openacc does not produce the correct final kinetic energy (i.e. Validation tests fail)
2. Poisson (C/C++ API) : mpi+openacc (when executed with more than 1 mpi proc) fails with error - 
   call to cuStreamSynchronize returned error 700: Illegal address during kernel execution
   call to cuMemFreeHost returned error 700: Illegal address during kernel execution
   (note that when executed with 1 mpi proc or executing the plain openacc will not give correct results)
3. Poisson (Fortran API) : mpi+openacc does not exist. openacc gives incorrect results
4. shsgc (Fortran API): mpi+openacc  (when executed with more than 1 mpi proc) fails with NaNs as the final result (but plain openacc passes and mpi+openacc with 1 proc gives correct results)

**Comment by gihanmudalige** [comment]
No 2. has been fixed in fix/openacc

**Comment by reguly** [comment]
Pushed in fix/openacc2 to address 3-4. CloverLeaf 3D still fails - I can see issues with advec_cell_kernel3_xdir and advec_cell_kernel4_xdir when switching OPS_GPU on and off - however there are no issues when I only run with a single process...
